<definitions name="getBanksService"
   targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
   xmlns="http://schemas.xmlsoap.org/wsdl/"
   xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
   xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
   xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <!-- message tags define data elements for each operation -->
   <message name="getBanksRequest">
       <part name="ssn" type="xsd:string"/>
       <part name="creditScore" type="xsd:string"/>
       <part name="loanAmount" type="xsd:string"/>
       <part name="loanDuration" type="xsd:string"/>
   </message>
  //message tags define data elements for each operation
   <message name="getBanksResponse">
      <part name="banks" type="xsd:float" maxOccurs="unbounded"/>
   </message>
   //describes operations performed by a port and the messages involved
   <portType name="Hello_PortType"> 
      <operation name="getBanks">
         <input message="tns:getBanksRequest"/>
         <output message="tns:getBanksResponse"/>
      </operation>
   </portType>
   //defines the protocol and data format for each port type
   <binding name="Hello_Binding" type="tns:Hello_PortType">
      <soap:binding style="rpc"
         transport="http://schemas.xmlsoap.org/soap/http"/>
      <operation name="getBanks">
         <soap:operation soapAction="getBanks"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
         </input>

         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:examples:helloservice"
               use="encoded"/>
         </output>
      </operation>
   </binding>

   <service name="getBanksService"> // defines the ports supported by remote service
      <documentation>WSDL File for HelloService</documentation>
      <!-- defines individual endpoint by a single address-->
      <port binding="tns:Hello_Binding" name="BANKS_Port">
         <soap:address
            location="http://localhost:3030/getBanks/" />
      </port>
   </service>
</definitions>
