<definitions name="HelloService"
             targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <!-- message tags define data elements for each operation -->
    <message name="loanRequest">
        <part name="ssn" type="xsd:string"/>
        <part name="creditScore" type="xsd:decimal"/>
        <part name="loanAmount" type="xsd:decimal"/>
        <part name="loanDuration" type="xsd:integer"/>
    </message>
    //message tags define data elements for each operation
    <message name="loanResponse">
        <part name="interestRate" type="xsd:decimal"/>
        <part name="ssn" type="xsd:string"/>
    </message>
    //describes operations performed by a port and the messages involved
    <portType name="Hello_PortType">
        <operation name="calculateInterest">
            <input message="tns:loanRequest"/>
            <output message="tns:loanResponse"/>
        </operation>
    </portType>
    //defines the protocol and data format for each port type
    <binding name="Hello_Binding" type="tns:Hello_PortType">
        <soap:binding style="rpc"
                      transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="calculateInterest">
            <soap:operation soapAction="calculateInterest"/>
            <input>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:helloservice"
                        use="encoded"/>
            </input>

            <output>
                <soap:body
                        encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
                        namespace="urn:examples:helloservice"
                        use="encoded"/>
            </output>
        </operation>
    </binding>

    <service name="interestService">// defines the ports supported by remote service
        <documentation>WSDL File for HelloService</documentation>
        <!-- defines individual endpoint by a single address-->
        <port binding="tns:Hello_Binding" name="interest_port">
            <soap:address
                    location="http://localhost:3038/calculateInterest/"/>
        </port>
    </service>
</definitions>